// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmQR1l9mPePn3co5-X6CjK700mg8HNFl4',
    appId: '1:162952114899:web:7e673bde235d10cf599a26',
    messagingSenderId: '162952114899',
    projectId: 'project-31cb3884-0cd8-4040-b0c',
    authDomain: 'project-31cb3884-0cd8-4040-b0c.firebaseapp.com',
    storageBucket: 'project-31cb3884-0cd8-4040-b0c.firebasestorage.app',
    measurementId: 'G-5FG7WPL7CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2uen7kzCWddSQ_IsPXGj9DtyH3ptf0E',
    appId: '1:162952114899:android:fa276bd9bcab64e8599a26',
    messagingSenderId: '162952114899',
    projectId: 'project-31cb3884-0cd8-4040-b0c',
    storageBucket: 'project-31cb3884-0cd8-4040-b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyCYX_uQEAB7qtc88NYmlU5g2b9Ol2wU',
    appId: '1:162952114899:ios:b63d7f692dbb47c3599a26',
    messagingSenderId: '162952114899',
    projectId: 'project-31cb3884-0cd8-4040-b0c',
    storageBucket: 'project-31cb3884-0cd8-4040-b0c.firebasestorage.app',
    iosBundleId: 'com.de-duke.app',
  );
}