// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8dACywz8W-e3z_HksgcTfsiec2ogAUJo',
    appId: '1:531781610440:web:b2aa9fec3547a23ffb2efd',
    messagingSenderId: '531781610440',
    projectId: 'de-duke-services',
    authDomain: 'de-duke-services.firebaseapp.com',
    storageBucket: 'de-duke-services.firebasestorage.app',
    measurementId: 'G-F2PZFNZ38G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6fM1Tkk68wICZZjcklsNOlUojAvLl2w',
    appId: '1:531781610440:android:b3d5d7150f64b005fb2efd',
    messagingSenderId: '531781610440',
    projectId: 'de-duke-services',
    storageBucket: 'de-duke-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0dcOaSN4l50TNFfO3PY3KY-WLEL9usE',
    appId: '1:531781610440:ios:2939c605214549c7fb2efd',
    messagingSenderId: '531781610440',
    projectId: 'de-duke-services',
    storageBucket: 'de-duke-services.firebasestorage.app',
    iosClientId: '531781610440-et9d0h1p68n6i86kenvvtkiudmb6tegb.apps.googleusercontent.com',
    iosBundleId: 'com.deduke.deDukeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0dcOaSN4l50TNFfO3PY3KY-WLEL9usE',
    appId: '1:531781610440:ios:2939c605214549c7fb2efd',
    messagingSenderId: '531781610440',
    projectId: 'de-duke-services',
    storageBucket: 'de-duke-services.firebasestorage.app',
    iosClientId: '531781610440-et9d0h1p68n6i86kenvvtkiudmb6tegb.apps.googleusercontent.com',
    iosBundleId: 'com.deduke.deDukeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8dACywz8W-e3z_HksgcTfsiec2ogAUJo',
    appId: '1:531781610440:web:bc1afa6d13fd7102fb2efd',
    messagingSenderId: '531781610440',
    projectId: 'de-duke-services',
    authDomain: 'de-duke-services.firebaseapp.com',
    storageBucket: 'de-duke-services.firebasestorage.app',
    measurementId: 'G-GB5Y0LVS79',
  );

}