import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/routing/app_router.dart';
import 'core/theme/app_theme.dart';
import 'firebase_options.dart';
import 'features/push_notifications/data/push_notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Required before any firebase_auth/cloud_firestore call (FEAT-010 chat)
  // and firebase_messaging call (FEAT-022 push). `DefaultFirebaseOptions`
  // comes from firebase_options.dart, generated by `flutterfire configure`
  // -- this deliberately does not crash app startup if initialization
  // fails (e.g. a dev machine without the Firebase config files yet);
  // chat screens surface a clear error via ChatRepository.ensureSignedIn()
  // at the point of use, and push registration degrades the same way (see
  // PushNotificationService.initialize's try/catch).
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // Must be registered before runApp, at top level (not a closure) --
    // firebase_messaging's own requirement, since this handler runs in a
    // separate isolate when the app is fully terminated.
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  } catch (_) {
    // Intentionally swallowed -- see comment above.
  }

  // Required for the Search feature's SearchNotifier (Riverpod
  // StateNotifier, see features/search/logic/search_providers.dart) --
  // confirmed real, pre-existing gap: `flutter_riverpod` was a dependency
  // and SearchResultsScreen was already a ConsumerStatefulWidget, but
  // nothing ever wrapped the app in a ProviderScope, so
  // `ConsumerStatefulElement.watch` threw "Bad state: No ProviderScope
  // found" the moment Search was actually reached at runtime (a router
  // change surfaced it, but the missing scope predates that change).
  runApp(const ProviderScope(child: DeDukeApp()));
}

class DeDukeApp extends StatelessWidget {
  const DeDukeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'De-Duke',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: ThemeMode.system,
      routerConfig: appRouter,
    );
  }
}
