import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/routing/app_keys.dart';
import 'core/routing/app_router.dart';
import 'core/theme/app_colors.dart';
import 'core/theme/app_theme.dart';
import 'firebase_options.dart';
import 'features/push_notifications/data/push_notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Required before any firebase_auth/cloud_firestore call (FEAT-010 chat)
  // and firebase_messaging call (FEAT-022 push). `DefaultFirebaseOptions`
  // comes from firebase_options.dart, generated by `flutterfire configure`
  // -- this deliberately does not crash app startup if initialization
  // fails (e.g. a dev machine without the Firebase config files yet);
  // chat screens surface a clear error via ChatRepository.ensureSignedIn()
  // at the point of use, and push registration degrades the same way (see
  // PushNotificationService.initialize's try/catch).
  try {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
    // Must be registered before runApp, at top level (not a closure) --
    // firebase_messaging's own requirement, since this handler runs in a
    // separate isolate when the app is fully terminated.
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  } catch (_) {
    // Intentionally swallowed -- see comment above.
  }

  // Required for the Search feature's SearchNotifier (Riverpod
  // StateNotifier, see features/search/logic/search_providers.dart) --
  // confirmed real, pre-existing gap: `flutter_riverpod` was a dependency
  // and SearchResultsScreen was already a ConsumerStatefulWidget, but
  // nothing ever wrapped the app in a ProviderScope, so
  // `ConsumerStatefulElement.watch` threw "Bad state: No ProviderScope
  // found" the moment Search was actually reached at runtime (a router
  // change surfaced it, but the missing scope predates that change).
  runApp(const ProviderScope(child: DeDukeApp()));
}

class DeDukeApp extends StatelessWidget {
  const DeDukeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'De-Duke',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: ThemeMode.system,
      routerConfig: appRouter,
      // Lets push_notification_service.dart's foreground FCM handler show
      // a MaterialBanner from outside the widget tree (see app_keys.dart) --
      // FCM only auto-displays a system notification for backgrounded/
      // terminated apps; a foregrounded app gets nothing on its own, so
      // this is the in-app equivalent for that case.
      scaffoldMessengerKey: rootScaffoldMessengerKey,
      // Android's system navigation bar (the OS-level back/home/recent-apps
      // chrome) otherwise stays at the platform default -- solid black --
      // regardless of the app's own theme, which reads as a jarring, un-
      // themed strip beneath every screen. `builder` runs inside
      // MaterialApp.router's own Theme, after light/dark/themeMode have
      // already resolved, so `Theme.of(context).brightness` here is always
      // the ACTUAL active brightness (correct under ThemeMode.system, and
      // still correct if that ever changes to a fixed mode) -- not a
      // re-derivation of MediaQuery's platform brightness, which could
      // briefly disagree with it. AnnotatedRegion applies globally (every
      // screen inherits it as a base), so this covers Scaffolds with no
      // AppBar of their own (e.g. Screen 1's Sign-Up/Login) exactly like
      // ones that do.
      builder: (context, child) {
        final isDark = Theme.of(context).brightness == Brightness.dark;
        return AnnotatedRegion<SystemUiOverlayStyle>(
          value: SystemUiOverlayStyle(
            systemNavigationBarColor:
                isDark ? AppColors.surfaceDark : AppColors.surface,
            systemNavigationBarIconBrightness:
                isDark ? Brightness.light : Brightness.dark,
            systemNavigationBarDividerColor: Colors.transparent,
            statusBarColor: Colors.transparent,
            statusBarIconBrightness:
                isDark ? Brightness.light : Brightness.dark,
            statusBarBrightness: isDark ? Brightness.dark : Brightness.light,
          ),
          child: child ?? const SizedBox.shrink(),
        );
      },
    );
  }
}
